import re

names = [
    "0xSARO|cryptoNFT.bitcoin",
    "0xSARO|cryptoNFT.eth",
    "0xSARO|cryptoNFT.vet",
    "0xSARO|cryptoNFT.algo",
    "0xSARO|cryptoNFT",
    "0xSARO|cryptoNFT.SARO",
    "\u4e50\u5564\u9152\u793e",
    "Saleh Ahmed",
    "Binance",
    "D13.coop",
    "Andrea-SP (PAZ) #ROMANFTWEEK Sept. 14 - 17 2023",
    "Laurence Fuller",
    "Laurence Fuller",
    "agash",
    "Laurence Fuller",
    "Laurence Fuller",
    "Laurence Fuller",
    "Laurence Fuller",
    "Laurence Fuller",
    "Laurence Fuller",
    "Laurence Fuller",
    "Laurence Fuller",
    "Marianne",
    "zaimiri \u270f\ufe0f",
    "Laurence Fuller",
    "\u24cb\u26a1\ufe0f",
    "b\u25cene \ud83e\uddb4",
    "MKei",
    "Carl",
    "K.I.L.A \u24cb",
    "Kermit \ud83d\udc38",
    "wale.swoosh \ud83d\udc33",
    "DogeDesigner",
    "SunSeeker 69 \u24cb \ud83d\udc10",
    "MB\u039e",
    "Moritz",
    "kennie.swoosh",
    "Myth",
    "Digi\ud83d\udc51",
    "cryptoleon \u26e9\ufe0f\ud83e\udd89\ud83d\udc38",
    "Noah",
    "Adri \ud835\udd4f",
    "GmanNFT",
    "RetroCat \ud83d\udd25",
    "Tone \u2615\ufe0f",
    "Junshi \ud83d\udc9c",
    "RIL\u039e \ud83c\udf0a",
    "Legendary",
    "Peter Sedlacik",
    "jacksonnnn \ud83e\udde8",
    "Justin \ud83c\udde6\ud83c\uddfa",
    "Polygon Dads 2.0: Coming soon",
    "King Degen\ud83d\udc51",
    "Myst \ud83d\udc51",
    "Zuzu\ud83e\udd0d",
    "Kryptcoin",
    "Mata \ud83d\udd25",
    "sli",
    "dubzy",
    "Drocif",
    "Alariann \ud83c\udfd7\ufe0f",
    "Lubo \u26a1\ufe0f",
    "Raven",
    "VePam \u24cb",
    "Kelano.eth",
    "xero \ud83c\udfae",
    "Fire Classic",
    "Chief Kief",
    "Laurence Fuller",
    "StonerPunks.vet",
    "vertigo",
    "Kx_",
    "MRC Arte \ud83e\udef6",
    "Poyo\ud83c\udf57",
    "Zeus",
    "OTT\u039eR\ud83e\udda6",
    "Jack \ud83e\uddcc",
    "Singer",
    "Christie\u26a1\ufe0f",
    "goldcat",
    "jack23",
    "Pops",
    "outrunyouth.eth",
    "TH\u039eGABO.\u039eTH",
    "Shrmurda\ud83c\udfcc\ufe0f\ud83c\udf92",
    "Conan \ud83d\udce3",
    "Mummy | Laura \ud83d\udc9c",
    "BOUBOY.eth",
    "Cheeky Crypto",
    "CABANA",
    "nftguyy",
    "Quantic \ud83d\udcab",
    "zavier",
    "daki3",
    "Zartash\ud83d\udca5",
    "\u26e9\ufe0fGuru\u26e9\ufe0f",
    "railaite.rob",
    "Nico",
    "\u2766 \ud835\udd94\ud835\udd93\ud835\udd89\ud835\udd86\ud835\udd98\ud835\udd8e\ud835\udd98\ud835\udd92\ud835\udd8e\ud835\udd88\ud835\udd86 LIMBO collection LIVE \u25fe",
    "SecretEscapeNFT \ud835\udd4d",
    "ken \ud83e\uddea",
    "freshy",
    "rex",
    "fity.eth",
    "redhouse_art.eth \ud83c\udf88\ud83c\udfb4",
    "tmas.eth \ud83d\udc41",
    "Chewie \u2078 \ud83e\uddec",
    "JJ",
    "GmanNFT",
    "GmanNFT",
    "Doodlegenics \ud83d\udc3b\ud83e\uddc3",
    "Dean A.K.A \u201c\ud83c\udf0a\u201d",
    "SPEED\u26a1\ufe0f",
    "LEDGE",
    "Etkin",
    "P\u039ennY",
    "\u2766 \ud835\udd94\ud835\udd93\ud835\udd89\ud835\udd86\ud835\udd98\ud835\udd8e\ud835\udd98\ud835\udd92\ud835\udd8e\ud835\udd88\ud835\udd86 LIMBO collection LIVE \u25fe",
    "Mik Cosentino",
    "Steak",
    "g-van \ud83d\udd87\ufe0f",
    "MinisterOfNFTs \ud83d\udd2e",
    "GmanNFT",
    "\ud83e\uddd1\ud83c\udffb\u200d\u2708\ufe0fCaptainKimi.eth",
    "VICTS",
    "GmanNFT",
    "GmanNFT",
    "StevieWildcards",
    "hercules.algo",
    "Mr. \ud83d\udd8d",
    "\u24cbalue",
    "\u2e38 \ud835\udd4d\ud835\udd52\ud835\udd5f\ud835\udd65\ud835\udd66\ud835\udd64 \u2e38",
    "GmanNFT",
    "GmanNFT",
    "Dclay \ud83e\ude99",
    "Laura Wolff",
    "Flam\u00e9",
    "X2Y2",
    "Henry\u2728SUPPORT ME ON PATREON\u2728\ud83e\udd70",
    "SuperVerseAI",
    "XParrots / XRPL \ud83e\udd9c",
    "Faraz Habiballahian",
    "Praise \ud81a\udd10\u023a\u20b3\ud83d\ude80",
    "GmanNFT",
    "DeltaSauce",
    "VICTS",
    "Tansu YE\u011eEN",
    "Edward J",
    "minner.algo",
    "KoolKong",
    "NFT God",
    "Lara",
    "Richard Nadler",
    "batz",
    "C3",
    "Mookie",
    "raccs",
    "Salvo",
    "Nick | SR \ud83d\udc8e",
    "pravijn",
    "shittykitties.algo",
    "MPetrelli",
    "KB (lil florida)",
    "Jana \ud83c\udde7\ud83c\uddf7",
    "snoozie",
    "Linda Yaccarino",
    "Cometa.algo",
    "bass\ud83c\udd71\ufe0fuddha",
    "Dew\ud83d\udca7",
    "Murtagh_BVM",
    "Yurii DeFi",
    "RECYOU1",
    "\u24cbeFoodies",
    "LUIS \u26a1",
    "SunSeeker 69 \u24cb \ud83d\udc10",
    "Moose",
    "AiKo",
    "Crypto-Ardent \u24cb \ud83d\udc10",
    "Jake Fried",
    "VICTS",
    "Killian Moore",
    "Rapha\u00ebl Erba",
    "Andrea Stroppa \ud83d\udc3a Claudius Nero's Legion \ud83d\udc3a",
    "Pak",
    "21"
]


def clean_twitter_account_name(account_name):
    # Remove emojis
    account_name = ''.join([char for char in account_name if not any(ord(c) > 127 for c in char)])

    # Remove "0x" at the beginning
    account_name = account_name.lstrip('0x')

    # Remove specific words and blacklisted words
    blacklist = [".bitcoin", ".eth", ".vet", ".algo", "nft"]
    words_to_remove = [word.lower() for word in blacklist]

    account_name_lower = account_name.lower()

    for word in words_to_remove:
        account_name_lower = account_name_lower.replace(word, "")

    # Remove tag after "|" or "-"
    account_name = re.split(r'[|-]', account_name_lower)[0].strip()

    if not account_name:
        return None

    #  Capitalize first letter of each word
    account_name = account_name.title()

    return account_name


for name in names:
    cleaned_account = clean_twitter_account_name(name)
    print(cleaned_account)
